name: Go Vulnerability Check
on: [pull_request]
jobs:
  govulncheck:
    name: Go Vulnerabilities Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Build OSM
        run: make build-osm
      - name: go vulnerabilities check
        run: govulncheck ./...